
const StringsName = {
  alert: 'ALERT',
  btnTitle: 'Get Started',
  back: 'back',
  next: 'Next',
  welcomeTxt: 'Welcome to CYI',
  bastPopularTxt: 'Best and popular apps for Post Your Idea',
  skip: 'SKIP',
  CheckYourIdeaTxt: 'Welcome to CHECK ',
  yourTxt: 'YOUR ',
  ideaTxt: ' IDEA',
  welcomeToLearnTxt: ' Welcome as you learn a world changing skill to get a better job. ',
  ChooseCourseTxt: 'Choose Your Course',
  ChooseIndustryKnowledgeTxt: "Choose the course of your choice and gain industry knowledge and experience in it.",
  getCertified: 'Get Certified',
  startLearning: 'Start learning and get certified after your training to get a lucrative job',
  loginTxt: 'Log In',
  loginTxt: 'Log In',
  email: 'Email',
  password: 'Password',
  enterCaptcher: 'Enter Captcha',
  stack: 'Captcha Code',
  forgotPassword: 'Forgot Password',
  donthaveAccount: `Don't have an account?`,
  alreadyhaveAccout: 'Already have an account?',
  signUp: 'Sign up',
  signIn: 'Sign in',
  firstName: 'First Name',
  lastName: 'Last Name',
  phoneNo: 'Phone No.',
  dateOfBirth: 'Date of birth',
  byYouAccept: 'By signing  you accept the ',
  termsOfServices: 'Terms of Services',
  and: 'and',
  privacyPolicy: 'Privacy Policy.',
  hello: 'Hello,',
  postyourIdea: `Post your `,
  idea: `Idea's`,
  all: 'ALL',
  Mostliked: 'MOST LIKED',
  new: 'NEW',
  random: 'RANDOM',
  readMore: 'Read More..',
  likes: 'Likes',
  dislikes: 'Dislikes',
  postyourIdeaAdd: 'Post your idea',
  title: 'Title',
  shortDescription: 'Short Description',
  longDescription: 'Long Description',
  cancle: 'Cancel',
  post: 'Post',
  support: 'Support',
  fullName: 'Full Name',
  emailId: 'Email Id',
  addComment: 'Add Comment',
  browse: 'Browse',
  submit: 'submit',
  updateProfile: 'Update Profile',
  profile: 'Profile',
  feedback: 'Feedback',
  aboutUs: 'About Us',
  myidea: 'MyIdea',
  myideas: "MyIdea's",
  changePassword: 'Change Password',
  logout: 'LOGOUT',
  editProfile: 'EditProfile',
  designation: 'Designation',
  location: 'Location',
  captchaCode: 'CaptchaCode',
  country: 'Country',
  emailAddress: 'Enter Email Address',
  send: 'Send',
  checkYourEmail: 'Check your email',
  weSendCode: 'We send a code to',
  fourDigitCode: 'enter 4 digit code that mentioned in the email',
  haveYouGotYet: 'Haven’t got the email yet? ',
  resendEmail: ' Resend email',
  verifyCode: 'Verify Code',
  createNewPassword: 'Create New Password ',
  newPassword: 'New Password ',
  confirmPassword: 'Confirm Password',
  proceed: 'PROCEED',
  passwordResetSuccessfully: 'Password Reset Successfully',
  loginWithNewPassword: 'You can login with your new password.',
  review: 'Review',
  latestIdea: `Latest Idea's`,
  NewIdeaiHere: 'My new idea is here',
  changeNewPassword: 'Type in your new password. Make sure it meets the required criteria',
  oldPassword: 'Old Password',
  passwordProtecttxt01: '• Lowercase & Uppercase',
  passwordProtecttxt02: '• Number (0-9)',
  passwordProtecttxt03: '• Special Character (!@#$%^&*)',
  passwordProtecttxt04: '• Atleast 8 Character',
  close:'Close',
  editYourPost:'Edit your Post'









};
export default StringsName;
